#' @title Shiny module for specifying respondent filter variables
#'
#' @description Generates an input switch for whether respondent filters should
#' be included or not, and if yes, a picker input that lists all variables from
#' which the filter variables should be chosen. Multiple filter variables can
#' be chosen.
#'
#' @param id Module ID
#'
#' @return
#' * UI: HTML tags that can be included in shiny's UI
#' * Server: a list with 3 reactive elements:
#'   + `inc_filters`: TRUE/FALSE. Status of the input switch for whether
#'   filters should be included
#'   + `filter_vars`: A named character vector of the variables to be used as
#'   respondent filters. To be passed to \link[datamods]{filter_data_server}.
#'   + `filter_dat`: A dataframe including the filter variables converted to
#'   factors.  To be passed to \link[datamods]{filter_data_server}.
#'
#' @export
#'
#' @name filterVariable
filterVariable_ui <- function(id) {
  ns <- shiny::NS(id)
  shiny::tagList(
    shiny::uiOutput(ns("inc_filters")),
    shiny::uiOutput(ns("filter_variables"))
  )
}

#' @param varLabels Dataframe (e.g. as generated by
#' \link[tveDataLoader]{get_varLabels}) containing two columns:
#' * `variable`: the variable names
#' * `label`: the variable labels
#' @param tab_data Response data to be tabled.
#'
#' @export
#'
#' @rdname filterVariable
filterVariable_server <- function(id, varLabels, tab_data) {
  shiny::moduleServer(
    id,
    function(input, output, session) {
      ns <- session$ns

      output$inc_filters <- shiny::renderUI({
        shinyWidgets::materialSwitch(
          inputId = ns("inc_filters2"),
          label = "Include respondent filters",
          value = FALSE,
          status = "primary"
        )
      })

      output$filter_variables <- shiny::renderUI({
        shiny::req(input$inc_filters2)

        if(input$inc_filters2 == TRUE) {
          choices <- dplyr::slice(varLabels(), -1) %>%
            dplyr::pull(label)

          shinyWidgets::pickerInput(
            ns("filter_vars"),
            label = "Filter variables",
            choices = choices,
            multiple = TRUE,
            options = list(
              `live-search` = TRUE
            )
          )
        }
      })

      filter_vars <- shiny::reactive({
        setNames(
          varLabels()[varLabels()$label %in% input$filter_vars, ]$variable,
          varLabels()[varLabels()$label %in% input$filter_vars, ]$label
        )
      })

      filter_dat <- shiny::reactive({
        dplyr::mutate(
          tab_data(),
          dplyr::across(tidyselect::all_of(as.character(filter_vars())), haven::as_factor)
        )
      })

      return(
        shiny::reactive({

          list(
            inc_filters = input$inc_filters2,
            filter_vars = filter_vars(),
            filter_dat = filter_dat()
          )
        })
      )

    }
  )
}
