#' Generate frequency / proportions table from survey data
#'
#' @param dat A dataframe containing the variables to be used as rows and
#' columns in the output table.
#' @param row_vars Character vector containing the variables to be used as rows
#' in the table.
#' @param col_var Character string containing the variables to be used as
#' columns in the output table.
#' @param weight_var Character string containing the variable name of the
#' weight to be used.
#' @param variable_labels A dataframe consisting of 2 columns:
#' 1. variable - the variable names of `dat`
#' 2. label - the variable labels of `dat`
#' As generated by \link[tveDataLoader]{get_varLabels}
#' @param percents TRUE if column percents required, FALSE If counts required.
#'
#' @importFrom rlang .data
#'
#' @export
generate_table <- function(dat,
                           row_vars,
                           col_var,
                           weight_var,
                           variable_labels,
                           percents = FALSE) {

  out <- dplyr::select(dat, dplyr::all_of(c(row_vars, col_var, weight_var))) %>%
    # add a specific column variable in case col_var is also selected as a row
    # variable
    dplyr::mutate(column = .data[[col_var]]) %>%
    # now reselect leaving out col_var unless it is in row_vars
    dplyr::select(dplyr::all_of(c(row_vars, weight_var)), column) %>%
    # if labelled convert to ordered factor
    dplyr::mutate(
      dplyr::across(
        where(labelled::is.labelled) & -tidyselect::all_of(weight_var),
        ~haven::as_factor(.x, ordered = TRUE)
      )
    ) %>%
    # if not labelled then must be a numeric var, convert to factor
    # levels in ascending order
    dplyr::mutate(
      dplyr::across(
        where(~!is.factor(.x)) & -tidyselect::all_of(weight_var),
        ~factor(.x, levels = sort(unique(.x)))
      )
    ) %>%
    # add explicit NA level
    dplyr::mutate(
      dplyr::across(
        -tidyselect::all_of(weight_var),
        forcats::fct_explicit_na
      )
    ) %>%
    # convert everything to character so that we can pivot longer
    dplyr::mutate(
      dplyr::across(
        -tidyselect::all_of(weight_var),
        as.character
      )
    ) %>%
    tidyr::pivot_longer(-c(tidyselect::all_of(weight_var), column)) %>%
    dplyr::group_by(dplyr::across(-tidyselect::all_of(weight_var))) %>%
    dplyr::count(wt = .data[[weight_var]]) %>%
    dplyr::ungroup() %>%
    tidyr::pivot_wider(
      names_from = column,
      values_from = n
    ) %>%
    dplyr::left_join(variable_labels, by = c("name" = "variable")) %>%
    dplyr::relocate(label, .after = name)

  if(percents == TRUE) {
    out <- out %>%
      dplyr::group_by(name) %>%
      dplyr::mutate(dplyr::across(-c(1:2), ~.x / sum(.x, na.rm = TRUE), 0))
  }


  names(out) <- c("Variable", "Label", "Value", names(out)[-c(1:3)])

  return(out)
}
