#' @title Shiny module for generating output table
#'
#' @description Produces an output table using \link{generate_table}, then
#' formats and renders as a DT data table (\link[DT]{renderDataTable}).
#'
#' @param id Module ID
#'
#' @export
#'
#' @name outputTab
outputTab_ui <- function(id) {
  ns <- NS(id)

  tagList(
    radioGroupButtons(
      inputId = ns("show_percents"),
      label = "Show percents or counts",
      choices = c("Column Percentages",
                  "Row Percentages",
                  "Counts"),
      selected = "Column Percentages"
    ),
    hr(),
    tags$strong("Output table"),
    DT::dataTableOutput(ns("out_tab"))
  )
}

#' @param dat Datatable to be summarised. See \link{generate_table} for
#' requirements.
#' @param filtering_exp Description of filters to be incorporated into the
#' output table's caption.
#' @param dat_file_name Name of the SPSS source file for inclusion in the
#' output table's caption.
#' @param weight_var Weighting variable to be applied. "No_weighting" if no
#' weighting to be applied.
#' @param row_var Variables from `dat` to be used as rows in the output table.
#' Intended to be generated by \link{slectionVars} but can also be a
#' character vector of variables names from `dat`.
#' @param col_var Variable from `dat` to be used as column breaks. Intended to
#' be generated by \link{selectionVars} but can also be a character vector of a
#' variable name from `dat`.
#' @param varLabels Dataframe (e.g. as generated by
#'  \link[tveDataLoader]{get_varLabels}) containing two columns:
#'
#' * `variable`: the variable names
#' * `label`: the variable labels
#'
#' @rdname outputTab
#'
#' @export
outputTab_server <- function(id,
                             dat,
                             filtering_exp,
                             dat_file_name,
                             weight_var,
                             row_var,
                             col_var,
                             variable_labels) {
  moduleServer(
    id,
    function(input, output, session) {
      ns <- session$ns

      expr <- reactive({
        # req(filtering_exp())
        expr <- toString(deparse(filtering_exp()))
        expr <- ifelse(is.null(filtering_exp()), "Total sample", expr)

        expr <- stringr::str_remove_all(expr, "%")
        expr <- stringr::str_replace_all(expr, "\\!", "NOT")
        expr <- paste("Sample definition:", expr)
        expr
      })

      meta <- reactive({
        paste(
          paste0("Data File: ", as.character(dat_file_name())),
          paste0("Filters: ", expr()),
          paste0("Weighting: ", stringr::str_replace(weight_var(), "_", " ")),
          sep = " | "
        )
      })

      # output table ----

      stat <- reactive({
        if(input$show_percents == "Column Percentages") {
          "columns"
        } else if (input$show_percents == "Row Percentages") {
          "rows"
        } else {
          "none"
        }
      })


      tab <- reactive({
        req(row_var())
        req(col_var())



        tab <- generate_table(
          dat(),
          row_var(),
          col_var(),
          weight_var(),
          variable_labels(),
          stat()
        )

        # fix order of table
        tab <- inner_join(
          get_valLabels(dat()) %>%
            filter(variable %in% row_var()) %>%
            select(-value),
          tab,
          by = c("variable" = "Variable", "value label" = "Value")
        ) %>%
          select(variable, Label, `value label`, everything())

        tab


      })

      output$out_tab <- DT::renderDataTable({
        req(col_var())


        col_label <- filter(variable_labels(), variable == col_var()) %>%
          pull(label)

        sketch = htmltools::withTags(table(
          class = 'display',
          thead(
            tr(
              th(rowspan = 2, 'Variable'),
              th(rowspan = 2, 'Label'),
              th(rowspan = 2, 'Value'),
              th(rowspan = 2, 'Total'),
              th(colspan = ncol(tab()) - 4, col_label)
            ),
            tr(
              lapply(names(tab())[-c(1:4)], th)
            )
          )
        ))

        out <- datatable(
          tab(),
          container = sketch,
          rownames = FALSE,
          extensions = c("Buttons", "RowGroup"),
          caption = meta(),
          options = list(
            dom = "Bplft",
            rowGroup = list(dataSrc = 1),
            buttons = c("copy", "csv", "excel"),
            pageLength = 100,
            lengthMenu = list(c(100, 200, 500, 1000, -1), c("100", "200", "500", "1000", "All")),
            scrollX = TRUE,
            scrollY = "800px",
            columnDefs = list(
              list(width = "50px", targets = c(0, 2)),
              list(width = "200px", targets = 1),
              list(width = "100px", targets = 3:(ncol(tab()) - 1))
            )
          )
        )

        if(stat() %in% c("columns", "rows")) {
          out <- out %>%
            formatPercentage(4:ncol(tab()), 2)
        }
        out

      })

      return(
        reactive({
          list(
            expr = expr(),
            # meta = meta(),
            dat = dat(),
            row_var = row_var(),
            col_var = col_var(),
            weight_var = weight_var(),
            variable_labels = variable_labels(),
            output_stat = stat(),
            tab = tab()
          )
        })

      )
    }
  )
}
