#' @title Shiny modules for specifying row and column variables
#'
#' @description
#' * `selectionVars_server`: Takes a variable labels dataframe, filters out
#' variables that should not be used for row / column breaks in the output
#' table, then \link[dplyr]{pull}s the variable labels, ready for passing into
#' `rowChoice` or `colChoice`. Intended to be used for convenience when the
#' same variables can be passed to both. No UI element.
#' * `rowChoice` allows specification of multiple variables to be
#'  used as rows in the output table.
#' * `colChoice` restricts selection to a single variable to be used as column
#' breaks in the output table.
#'
#' @param id Module ID
#' @param varLabels Dataframe (e.g. as generated by
#'  \link[tveDataLoader]{get_varLabels}) containing two columns:
#' * `variable`: the variable names
#' * `label`: the variable labels
#' @param exclude character vector of variable names to exclude
#'
#' @return
#' * `selectionVars_server`: Character vector of the variable labels that can
#' be chosen. Intended to be stored as a reactive then passed to `rowChoice` or
#' `colChoice` in the instance where the same set of variables can be used for
#' both.
#' * `rowChoice` / `colChoice`:
#'   + UI: HTML tags that can be included in shiny's UI
#'   + server: Character vector of the variable labels to be used as row /
#'   column breaks respectively.
#'
#' @export
#'
#' @name selectionVars
selectionVars_server <- function(id, varLabels, exclude) {
  shiny::moduleServer(
    id,
    function(input, output, session) {
      selection_vars <- shiny::reactive({

        shiny::req(varLabels())
        shiny::req(exclude)

        dplyr::filter(varLabels(), !variable %in% exclude) %>%
          dplyr::slice(-1) %>%
          dplyr::pull(label)
      })
      return(selection_vars)
    }
  )
}

#' @export
#' @rdname selectionVars
rowChoice_ui <- function(id) {
  ns <- shiny::NS(id)
  shiny::uiOutput(ns("row_choice"))
}

#' @param selection_vars Reactive character vector of the variable labels from
#' which users can select row / column breaks. Can be generated by
#' `selectionVars_server` or input manually.
#' @export
#' @rdname selectionVars
rowChoice_server <- function(id, selection_vars, varLabels) {
  shiny::moduleServer(
    id,
    function(input, output, session) {
      ns <- session$ns

      output$row_choice <- shiny::renderUI({

        shiny::req(selection_vars())

        shinyWidgets::pickerInput(
          ns("row_vars"),
          label = "Row variables",
          choices = selection_vars(),
          multiple = TRUE,
          options = list(
            `live-search` = TRUE,
            `actions-box` = TRUE
          )
        )
      })

      row_variables <- shiny::reactive({
        dplyr::filter(varLabels(), label %in% input$row_vars) %>%
          dplyr::pull(variable)
      })

      return(row_variables)

    }
  )
}

#' @export
#' @rdname selectionVars
colChoice_ui <- function(id) {
  ns <- shiny::NS(id)
  shiny::uiOutput(ns("col_choice"))
}

#' @export
#' @rdname selectionVars
colChoice_server <- function(id, selection_vars, varLabels) {
  shiny::moduleServer(
    id,
    function(input, output, session) {
      ns <- session$ns

      output$col_choice <- shiny::renderUI({

        shiny::req(selection_vars())

        shinyWidgets::pickerInput(
          ns("column_variable"),
          label = "Column Variables",
          choices = selection_vars(),
          options = list(
            `live-search` = TRUE,
            `actions-box` = TRUE
          )
        )
      })

      column_variables <- shiny::reactive({
        dplyr::filter(varLabels(), label %in% input$column_variable) %>%
          dplyr::pull(variable)
      })

      return(column_variables)

    }
  )
}
