#' @title Shiny module for specifying a weighting variable
#'
#' @description Generates an input switch for whether a weight variable should
#' be used, and if set to yes, a picker input listing all variables from the
#' data apart from the first (which is assumed to be respid).
#'
#' @param id Module ID
#'
#' @return
#' * UI: HTML tags that can be included in shiny's UI
#' * Server: A string of either the weight variables name or "no_weighting" if
#' no weight is selected
#'
#' @export
#'
#' @name weightVariable
weightVariable_ui <- function(id) {
  ns <- NS(id)
  tagList(
    uiOutput(ns("inc_weight")),
    uiOutput(ns("weight_variable"))
  )
}

#' @param varLabels Dataframe (e.g. as generated by
#'  \link[tveDataLoader]{get_varLabels}) containing two columns:
#'
#' * `variable`: the variable names
#' * `label`: the variable labels
#'
#' @rdname weightVariable
#'
#' @export
weightVariable_server <- function(id, varLabels) {
  moduleServer(
    id,
    function(input, output, session) {
      ns <- session$ns

      output$inc_weight <- renderUI({
        req(varLabels)
        shinyWidgets::materialSwitch(
          inputId = ns("inc_weight2"),
          label = "Include weighting variable",
          value = FALSE,
          status = "primary"
        )
      })

      output$weight_variable <- renderUI({
        req(input$inc_weight2)
        if(input$inc_weight2 == TRUE) {
          choices <- slice(varLabels(), -1) %>% pull(label)

          shinyWidgets::pickerInput(
            ns("weight_var"),
            label = "Weight variable",
            choices = choices,
            options = list(
              `live-search` = TRUE
            )
          )
        }
      })

      return(
        reactive({

          if(input$inc_weight2 == TRUE) {
            weight <- filter(varLabels(), label %in% input$weight_var) %>%
              pull(variable)
          } else {
            weight <- "no_weighting"
          }

          weight
        })
      )
    }
  )
}
